name: Enterprise DevSecOps Pipeline

on:
  push:
    branches:
      - main
      - fully-automated-devsecops

permissions:
  contents: read
  security-events: write

jobs:

  security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Install Semgrep
        run: |

          python3 -m pip install semgrep

      - name: Run Semgrep Scan
        run: |

          semgrep scan \
          --config auto \
          --exclude node_modules \
          .
        continue-on-error: true

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 0

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform,dockerfile
          soft_fail: true

  build-and-push:

    runs-on: ubuntu-latest

    needs: security-scan

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch DockerHub Credentials From Vault
        run: |

          sudo apt-get update

          sudo apt-get install jq -y

          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}

          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}

          curl \
          --silent \
          --header "X-Vault-Token: $VAULT_TOKEN" \
          $VAULT_ADDR/v1/secret/data/dockerhub \
          > dockerhub.json

          echo "DOCKER_USERNAME=$(jq -r '.data.data.username' dockerhub.json)" >> $GITHUB_ENV

          echo "DOCKER_PASSWORD=$(jq -r '.data.data.password' dockerhub.json)" >> $GITHUB_ENV

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |

          docker build \
          -t $DOCKER_USERNAME/enterprise-devsecops-app:latest \
          .

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/enterprise-devsecops-app:latest
          format: table
          exit-code: 0

      - name: Push Docker Image
        run: |

          docker push \
          $DOCKER_USERNAME/enterprise-devsecops-app:latest

  terraform-provision:

    runs-on: ubuntu-latest

    needs: build-and-push

    outputs:
      public_ip: ${{ steps.getip.outputs.public_ip }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch AWS Credentials From Vault
        run: |

          sudo apt-get update

          sudo apt-get install jq -y

          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}

          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}

          curl \
          --silent \
          --header "X-Vault-Token: $VAULT_TOKEN" \
          $VAULT_ADDR/v1/secret/data/aws \
          > aws.json

          echo "AWS_ACCESS_KEY_ID=$(jq -r '.data.data.AWS_ACCESS_KEY_ID' aws.json)" >> $GITHUB_ENV

          echo "AWS_SECRET_ACCESS_KEY=$(jq -r '.data.data.AWS_SECRET_ACCESS_KEY' aws.json)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create SSH Private Key
        run: |

          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem

          chmod 400 private_key.pem

      - name: Create SSH Public Key
        run: |

          ssh-keygen -y -f private_key.pem > public_key.pub

      - name: Move Public Key
        run: |

          mkdir -p terraform/keys

          cp public_key.pub terraform/keys/id_rsa.pub

      - name: Terraform Init
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        run: |

          terraform init

      - name: Terraform Validate
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        run: |

          terraform validate

      - name: Terraform Apply
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        run: |

          terraform apply -auto-approve

      - name: Get EC2 Public IP
        id: getip
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        run: |

          PUBLIC_IP=$(terraform output -raw deployment_server_ip)

          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT

  deploy:

    runs-on: ubuntu-latest

    needs: terraform-provision

    steps:

      - name: Fetch DockerHub Credentials From Vault
        run: |

          sudo apt-get update

          sudo apt-get install jq -y

          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}

          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}

          curl \
          --silent \
          --header "X-Vault-Token: $VAULT_TOKEN" \
          $VAULT_ADDR/v1/secret/data/dockerhub \
          > dockerhub.json

          echo "DOCKER_USERNAME=$(jq -r '.data.data.username' dockerhub.json)" >> $GITHUB_ENV

      - name: Create SSH Key
        run: |

          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem

          chmod 400 private_key.pem

      - name: Wait For EC2 Initialization
        run: |

          sleep 120

      - name: Deploy Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.terraform-provision.outputs.public_ip }}
          username: ubuntu
          key_path: private_key.pem
          script: |

            docker pull $DOCKER_USERNAME/enterprise-devsecops-app:latest

            docker rm -f dev-container || true

            docker rm -f staging-container || true

            docker rm -f production-container || true

            docker run -d \
            --name dev-container \
            -p 3000:3000 \
            $DOCKER_USERNAME/enterprise-devsecops-app:latest

            docker run -d \
            --name staging-container \
            -p 3001:3000 \
            $DOCKER_USERNAME/enterprise-devsecops-app:latest

            docker run -d \
            --name production-container \
            -p 3002:3000 \
            $DOCKER_USERNAME/enterprise-devsecops-app:latest

      - name: Deployment Completed
        run: |

          echo "Enterprise DevSecOps Pipeline Completed Successfully"
